# Default values for rh-acs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
acs:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  operatorNamespace: rhacs-operator
  namespace: stackrox
  cliImage: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# acs<bool>: 'true' or 'false' - Controls whether Advanced Cluster Security is managed
#
# Configuration:
# acs-name<String>: Operator subscription name (default: 'rhacs-operator')
# acs-channel<String>: Operator channel (default: 'stable')
# acs-install-plan-approval<String>: 'Automatic' or 'Manual' (default: 'Automatic')
# acs-source<String>: Operator catalog source (default: 'redhat-operators')
# acs-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/acs: 'true'
# autoshift.io/acs-channel: 'stable'
# autoshift.io/acs-install-plan-approval: 'Automatic'
# autoshift.io/acs-source: 'redhat-operators'
# autoshift.io/acs-source-namespace: 'openshift-marketplace'